Dev/tungbt/#77
alitonia/multi-choice-system pull request #107
Opened 2021-12-28 13:46 UTC by narutox900

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 77

## What is the new behavior?

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

## Other information

2021-12-28 13:49 UTC, alitonia commented
Cái này ông merge main vào nhánh rồi đẩy lại lên nhá. Api đổi nhiều nên đang nhiều conflict

2021-12-28 16:22 UTC, narutox900 commented
> Cái này ông merge main vào nhánh rồi đẩy lại lên nhá. Api đổi nhiều nên đang nhiều conflict

merged

2021-12-30 17:28 UTC, alitonia requested changes
Có cái api /exam/get/{exam_id} chọn 1 cái là ok, hoặc là đổi lại endpoint

2021-12-30 17:28 UTC, alitonia commented on backend/src/app/api/exam/router.py
> +@router.get("/exam/get/{exam_id}", response_model=ExamSchemaOut)
Phần nay trùng api với https://github.com/alitonia/multi-choice-system/blob/b371f274ed6a78c6ddf3a93b3d9229b05319bae1/backend/src/app/api/exam/router.py#L37 à?

2021-12-30 17:32 UTC, narutox900 commented on backend/src/app/api/exam/router.py
> +@router.get("/exam/get/{exam_id}", response_model=ExamSchemaOut)
> Có cái api /exam/get/{exam_id} chọn 1 cái là ok, hoặc là đổi lại endpoint

ok sẽ đổi tên nhé, t ko để ý

2021-12-31 03:36 UTC, narutox900 commented on backend/src/app/api/exam/router.py
> +@router.get("/exam/get/{exam_id}", response_model=ExamSchemaOut)
đã đổi nhé

2021-12-31 03:37 UTC, narutox900 commented on backend/src/app/api/exam/router.py
> +@router.get("/exam/get/{exam_id}", response_model=ExamSchemaOut)
@tuanb11a2  @hha1501 integrate với FE và check lại nhé

2021-12-31 10:44 UTC, narutox900 commented
t có thấy `@router.get("/exam/{exam_id}"` trùng với cái nào nữa đâu nhỉ @alitonia

2021-12-31 10:46 UTC, alitonia commented
Bên dưới trùng với add_examinee với remove_examinee ý ông.
Nếu mà ông thấy cần thì đổi vị trí cho nó khỏi trùng nhá, tôi tạm comment đi cho frontend làm đã.

2021-12-31 10:50 UTC, narutox900 commented
cái `@router.get("/exam/get_examinees")` t nghĩ nên để exam_id lên thành `/exam/{exam_id}/examinees` thì hay hơn

2021-12-31 10:57 UTC, alitonia commented
Cái này @DatPth410  ông thấy có ảnh hưởng gì không?

2021-12-31 14:47 UTC, alitonia commented
Theo tôi thì phần add examinee đang chạy rồi, không nên động vào nữa. Phần api Get exam/{exam_id} nếu cần dùng thì có thể đổi qua exam/get_alternative/{exam_id} để không bị trùng.

2021-12-31 14:49 UTC, narutox900 commented
t đang test với Linh và thấy vẫn gọi được bình thường, ko bị trùng nhé

2022-01-01 14:59 UTC, alitonia commented
Will merge this in https://github.com/alitonia/multi-choice-system/pull/86

2022-01-01 14:59 UTC, closed without merging