Ops/alitonia/query hooks
alitonia/multi-choice-system pull request #82
Opened 2021-12-17 08:14 UTC by alitonia

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

* No query hook

Issue Number: N/A

## What is the new behavior?

* Added query hook
* Added fake query hook as data placeholder

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2021-12-17 08:17 UTC, leehoang2000 reviewed
hitnDict.js or hintDict.js

2021-12-17 08:27 UTC, alitonia commented
Fixed to hint 🙄

2021-12-18 16:34 UTC, linh442k requested changes

2021-12-18 16:34 UTC, linh442k commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +});
data exam
thiếu teacher name, 
start_time nên để Unix timestamps in seconds hoặc milliseconds, cho dễ xử lý không cần parse string ở fe
duration để là phút

2021-12-18 16:36 UTC, linh442k commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +
fe ko cần trường is_correct đâu :v

2021-12-18 16:38 UTC, linh442k commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +
grading rule khả năng fe cũng ko dùng
không rõ question_group để làm gì á @@

2021-12-18 16:42 UTC, linh442k requested changes

2021-12-18 16:42 UTC, linh442k commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +
enable là gì nhỉ, ngoài ra trong design toi thấy có cả role ADMIN
ngoài ra 1 account cũng cần có major, class nữa
dob để dạng dd-mm-yyyy cho chuẩn design nhé ô :v

2021-12-18 16:53 UTC, linh442k commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +    questionsExaminee: _dataQuestionsExaminee,
3 cái question, questionExaminer, questionExaminee khác nhau ntn nhỉ? Examinee khi làm bài kiểm tra thì fetch về cái nào? Khi gửi data bài ktra lên server thì dùng cái nào?

2021-12-18 17:20 UTC, alitonia commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +
* enable là thuộc tính xem account có hoạt động không.
* cái này là mock thôi, còn admin tôi thấy không quan trọng lắm nên không cho vào. Nếu mà cần đầy đủ logic thì ông dùng API nhá
* dob ông muốn dd-mm-yyyy cho mỗi giá trị trả về hay cả lúc gửi đi nữa?

2021-12-18 17:30 UTC, alitonia commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +    questionsExaminee: _dataQuestionsExaminee,
Cái này ông nhìn trong API draft nhá:
* question là 1 giá trị
* questionsExaminer là cái có nhiều giá trị
* questionsExaminee là cái dùng để lấy lúc làm bài thi, có cả choice.
Lúc lấy bài kiểm tra thì lấy questionsExaminee, là lấy cả 1 cuc luôn.
Lúc gửi lên server thì theo draft là gửi 1 question 1, xong câu nào gửi câu ý để có dữ liệu hồi phục khi examinee ded, thì theo question nha.

2021-12-18 17:41 UTC, alitonia commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +});
Trên draft thì data trả về không có creator, ông có cần creator để làm gì không?
start-time trên db đang để là timestamp, duration để là time. Giờ nhiều người đang làm tôi đang muốn tránh chỉnh lại database. 2 cái này ông có thể parse ở frontend nha :">

2021-12-19 01:54 UTC, linh442k commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +});
Ở trang exam page ấy ô, cần có teacher name
duration với start-time trả về ntn thì hơi cực cho fe lúc parse thôi ô :v
nhất là start_time.

2021-12-19 01:56 UTC, linh442k commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +
format của dob thì nên để dd-mm-yyyy tất cả luôn ô ạ

2021-12-19 01:59 UTC, linh442k commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +    questionsExaminee: _dataQuestionsExaminee,
cái lấy 1 cục questionExaminee thì hợp lý rồi
còn cái gửi lên server thì toi đang định là khi hết giờ hoặc submit thì fe gửi 1 cục luôn; chứ xong câu nào gửi câu ấy thì có vẻ hơi nặng server, nhỡ examinee quay lại câu hỏi cũ để thay đổi nữa

2021-12-19 03:10 UTC, linh442k commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +    questionsExaminee: _dataQuestionsExaminee,
also trong question page của examinee cũng cần có exam info nhé

2021-12-19 07:17 UTC, alitonia commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +});
JS có parseDate mà ông. Confirm là sẽ sửa ở commit sau.

2021-12-19 07:20 UTC, alitonia commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +    questionsExaminee: _dataQuestionsExaminee,
Cái gửi từng câu 1 là để nếu examinee bị drop thì khôi phục được.
Exam_info thì lấy từ exam data.

2021-12-19 07:55 UTC, linh442k commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +});
oke thế cái date thì chưa cần sửa format đâu, nhưng data exam thì cần có teacher name ông nhé.

2021-12-19 07:59 UTC, linh442k commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +    questionsExaminee: _dataQuestionsExaminee,
oke thế chốt là mỗi lần đáp án của examinee có thay đổi thì gủi question lên server nhé

2021-12-19 10:25 UTC, linh442k commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +
Account cũng nên có id nhé ông, lúc bấm edit còn biết là edit ông id nào

2021-12-20 09:34 UTC, linh442k commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +
account cũng nên có 1 trường id riêng ông nhé

2021-12-22 17:52 UTC, alitonia commented
Hmm tôi thấy resolved hết rồi mà review vẫn chưa xong. @linh442k ông xem review chuyển sang accepted được chưa nha, để tôi merge lên main.

2021-12-23 02:14 UTC, linh442k commented
> Hmm tôi thấy resolved hết rồi mà review vẫn chưa xong. @linh442k ông xem review chuyển sang accepted được chưa nha, để tôi merge lên main.

toi  thì thấy oke rồi không biết các ô khác ntn thôi

2021-12-23 03:43 UTC, linh442k approved these changes

2021-12-23 05:43 UTC, alitonia commented on frontend/src/hooks/queryFamily/fakeQuery/hintDict.js
> +    }
Ok. Tôi thêm ở https://github.com/alitonia/multi-choice-system/pull/82/commits/46580b89174f1e59c760d58178bddc57ad73b383 rồi nha

2021-12-23 05:44 UTC, alitonia commented
Thế thì cứ merge đã, ai cần fĩx thì lại mở cái khác

2021-12-23 05:44 UTC, merged