exam page and question page FE mockup
alitonia/multi-choice-system pull request #86
Opened 2021-12-18 15:28 UTC by linh442k

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: 77

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2021-12-18 17:43 UTC, alitonia commented
Tôi thấy đang dùng var trong code, ông chạy lint chưa ( yarn lint:fix) ?

2021-12-19 02:15 UTC, linh442k commented
oke toi đã chạy lint fix nhé

2021-12-19 08:01 UTC, linh442k commented
đây mới là mockup chứ chưa phải bản final nhé

2021-12-23 09:11 UTC, alitonia requested changes
Chuyển qua dùng yarn cho đồng bộ nha ông, rồi xoá package-lock.json đi. Còn lại là ok rồi.

2021-12-23 10:36 UTC, linh442k commented
> Chuyển qua dùng yarn cho đồng bộ nha ông, rồi xoá package-lock.json đi. Còn lại là ok rồi.

Đừng merge vội nhé, chưa xong đâu

2021-12-23 14:01 UTC, linh442k commented
chuyển questionPage sang questionPage/:id
dùng data từ fake query

2021-12-28 15:53 UTC, alitonia requested changes
Cần chỉnh lại một số chỗ là ok:
* Cắm api
* Cắm token
* Xóa bớt comment nếu có thế 🤠
* Chạy yarn lint:fix trước khi commit (không bắt buộc)

2021-12-28 15:53 UTC, alitonia commented on frontend/src/pages/ExamPage/index.js
> +        "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjUwMDAsImV4cCI6MTY0MDcyNDEwNy44MzI2MjAxfQ.S5QTCWhCbj-8ZCRw1XIF6IWjJUf920we1p_a4-cdqdw";
Cắm token vào nh

2021-12-28 15:53 UTC, alitonia commented on frontend/src/pages/ExamPage/index.js
> +        // console.log(id)
Không dùng thì xóa đi cho sạch đẹp nh

2021-12-28 15:53 UTC, alitonia commented on frontend/src/pages/QuestionPage/index.js
> +        setExamInfo({
Cái này thay bằng api giúp tôi nha

2021-12-28 15:53 UTC, alitonia commented on frontend/src/pages/QuestionPage/index.js
> +        hours: "xx",
Phần này thay bằng số thật nha

2021-12-28 15:53 UTC, alitonia commented on frontend/src/pages/QuestionPage/questionData.js
> +const a = '[{"question_id":"431","question_content":"content for 1","exam_id":"211","question_group":[{"question_group_id":1,"description":"TEST_QT_1"}],"question_type":[{"question_type_id":2,"descri
Cái này khi nào cắm được api vào thì bỏ đi nhé.

2021-12-28 17:54 UTC, linh442k commented
Chưa cắm api thật nên coi như chưa xong nha @@

2021-12-30 17:56 UTC, alitonia commented
API ok rồi đó https://github.com/alitonia/multi-choice-system/pull/107, ông cắm vào nha

2021-12-31 04:08 UTC, linh442k commented
> API ok rồi đó #107, ông cắm vào nha

api gì đấy ô?

2022-01-01 04:02 UTC, linh442k commented
đã nối api xong, @alitonia @DrakeGoCoding @leehoang2000 check giúp tôi nhé!

2022-01-01 04:04 UTC, DrakeGoCoding commented
Ok

2022-01-01 15:00 UTC, alitonia approved these changes
Working flow

2022-01-01 15:00 UTC, merged